import pyautogui as py 
import time as ti

print ("1. Hardbass")
print ("2.Emo Playlist")
print ("3. Lieblingssongs")

user_input=input ()

if user_input == '1':
    py.moveTo (x=1276, y=21)
    py.click ()
    ti.sleep (3)
    py.moveTo (x=2529, y=117)
    py.click ()
    py.sleep (1)
    py.moveTo (x=2329, y=161)
    py.sleep (2)
    py.write ('https://open.spotify.com/playlist/0e1hDulpl5MjUVN3iVmL5b')
    py.press ('enter')
    ti.sleep (3)
    py.moveTo (x=1169, y=1372)
    py.click ()
    ti.sleep (0.5)
    py.moveTo (x=378, y=660)
    py.click ()
elif user_input == '2':
    py.moveTo (x=1276, y=21)
    py.click ()
    ti.sleep (3)
    py.moveTo (x=2529, y=117)
    py.click ()
    py.sleep (1)
    py.moveTo (x=2329, y=161)
    py.sleep (2)
    py.write ('https://open.spotify.com/playlist/2T0QojUouaWJnDwNQ10drp')
    py.press ('enter')
    ti.sleep (3)
    py.moveTo (x=1169, y=1372)
    py.click ()
    ti.sleep (0.5)
    py.moveTo (x=378, y=660)
    py.click ()
elif user_input == '3':
    py.moveTo (x=1276, y=21)
    py.click ()
    ti.sleep (3)
    py.moveTo (x=2529, y=117)
    py.click ()
    py.sleep (1)
    py.moveTo (x=2329, y=161)
    py.sleep (2)
    py.write ('https://open.spotify.com/collection/tracks')
    py.press ('enter')
    ti.sleep (3)
    py.moveTo (x=1169, y=1372)
    py.click ()
    ti.sleep (0.5)
    py.moveTo (x=378, y=660)
    py.click ()